"""Narrow native methods exposed to the bundled desktop workbench."""

from __future__ import annotations

import base64
import json
import os
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit
from urllib.request import HTTPRedirectHandler, Request, build_opener

from .native import external_web_url, is_workbench_url

MAX_EXPORT_BYTES = 32 * 1024 * 1024
EXPORT_SUFFIXES = {".csv", ".tsv", ".txt", ".json", ".png", ".svg", ".html", ".md", ".zip", ".xlsx", ".pdf"}


def export_filename(value: str) -> str:
    name = str(value or "export.txt").replace("\\", "/").rsplit("/", 1)[-1]
    name = "".join(ch for ch in name if ord(ch) >= 32 and ch not in '<>:"|?*').strip(" .")
    if not name or len(name) > 200 or Path(name).suffix.lower() not in EXPORT_SUFFIXES:
        raise ValueError("Unsupported export filename")
    return name


def known_result_file(path: Path) -> bool:
    """Validate exact saved outputs, rather than trusting a parent input directory."""
    from electrochem_v6.config import user_config_dir
    from electrochem_v6.store.runtime import get_database

    target = os.path.normcase(str(path.resolve()))
    database = get_database()
    with database.read() as connection:
        rows = connection.execute("SELECT output_files FROM history_records").fetchall()
        recipes = connection.execute("SELECT value FROM meta WHERE key LIKE 'run_recipe:%'").fetchall()
    candidates = []
    for row in rows:
        candidates.extend(json.loads(row["output_files"] or "[]"))
    for row in recipes:
        recipe = json.loads(row["value"])
        outputs = recipe.get("outputs") or {}
        if isinstance(outputs, dict):
            candidates.extend(outputs.get("output_files") or [])
        candidates.extend(recipe.get("output_files") or [])
        for key in ("manifest_path", "report_html_path", "report_md_path"):
            if recipe.get(key):
                candidates.append(recipe[key])
    for candidate in candidates:
        if isinstance(candidate, dict):
            candidate = candidate.get("path")
        if isinstance(candidate, str) and os.path.normcase(str(Path(candidate).resolve())) == target:
            return True
    # Project reports are generated by the application under this dedicated root.
    report_root = (user_config_dir() / "project_reports").resolve()
    return path.resolve().is_relative_to(report_root)


class _NoRedirect(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        raise ValueError("Export redirects are not supported")


class DesktopBridge:
    def __init__(self, app: Any) -> None:
        self._app = app

    def _check_origin(self) -> None:
        window = self._app.window
        if not window or not is_workbench_url(window.get_current_url() or "", self._app.ui_url):
            raise ValueError("Native actions are available only in the local workbench")

    def get_state(self) -> dict[str, Any]:
        self._check_origin()
        return self._app.get_state()

    def get_environment_report(self) -> dict[str, Any]:
        self._check_origin()
        from .environment import collect_environment_report, format_environment_report

        report = collect_environment_report(self._app.runtime_root, self._app.location)
        return {"status": "success", "report": report, "report_text": format_environment_report(report)}

    def save_preferences(self, preferences: Any) -> dict[str, Any]:
        self._check_origin()
        return {"status": "success", "preferences": self._app.state.save_preferences(preferences)}

    def set_window_appearance(self, appearance: Any) -> dict[str, Any]:
        self._check_origin()
        return self._app.set_window_appearance(appearance)

    def choose_import_files(self) -> dict[str, Any]:
        self._check_origin()
        if self._app.closing_mode:
            return {"status": "error", "message": "客户端正在等待任务结束，暂不接收新数据。"}
        paths = self._app.window.create_file_dialog(10, allow_multiple=True, file_types=("Data (*.txt;*.csv)",))
        return {"status": "success", "file_paths": self._app.validate_input_files(paths or [])}

    def _select_paths(self, kind: str, initial: str = "", extensions: Any = None) -> dict[str, Any]:
        """Use the active webview's main-thread native dialog on every desktop OS."""
        self._check_origin()
        if self._app.closing_mode:
            return {"status": "error", "message": "客户端正在等待任务结束，暂不接收新数据。"}
        from electrochem_v6.core.system_service import register_allowed_dir

        initial_path = Path(str(initial or self._app.data_dir)).expanduser()
        directory = initial_path if initial_path.is_dir() else initial_path.parent
        if not directory.is_dir():
            directory = Path(self._app.data_dir)
        options: dict[str, Any] = {"directory": str(directory.resolve()), "allow_multiple": kind == "files"}
        suffixes: set[str] = set()
        if kind != "folder":
            supplied = extensions if isinstance(extensions, list) and extensions else [".txt", ".csv"]
            if len(supplied) > 32:
                raise ValueError("Too many file extensions")
            for value in supplied:
                suffix = "." + str(value or "").strip().lstrip(".").lower()
                if not re.fullmatch(r"\.[a-z0-9]{1,12}", suffix):
                    raise ValueError("Unsupported file extension")
                suffixes.add(suffix)
            options["file_types"] = ("Data (" + ";".join("*" + value for value in sorted(suffixes)) + ")",)
        paths = self._app.window.create_file_dialog(20 if kind == "folder" else 10, **options)
        if not paths:
            return {"status": "error", "message": "未选择文件夹" if kind == "folder" else "未选择文件"}
        if isinstance(paths, str):
            paths = [paths]
        if not isinstance(paths, (tuple, list)) or len(paths) > 1000 or (kind != "files" and len(paths) != 1):
            raise ValueError("Unexpected native selection")
        selected = []
        for value in paths:
            path = Path(str(value)).resolve()
            valid = path.is_dir() if kind == "folder" else path.is_file() and path.suffix.lower() in suffixes
            if not valid:
                raise ValueError("The selected path is unavailable or its file type is unsupported")
            selected.append(str(path))
        selected = list(dict.fromkeys(selected))
        for path_value in selected:
            path = Path(path_value)
            register_allowed_dir(str(path if kind == "folder" else path.parent))
        if kind == "folder":
            return {"status": "success", "folder_path": selected[0]}
        if kind == "file":
            return {"status": "success", "file_path": selected[0]}
        return {"status": "success", "file_paths": selected, "count": len(selected)}

    def select_folder(self, initial_dir: str = "") -> dict[str, Any]:
        return self._select_paths("folder", initial_dir)

    def select_file(self, initial_path: str = "", extensions: Any = None) -> dict[str, Any]:
        return self._select_paths("file", initial_path, extensions)

    def select_files(self, initial_path: str = "", extensions: Any = None) -> dict[str, Any]:
        return self._select_paths("files", initial_path, extensions)

    def _save(self, contents: bytes, filename: str) -> dict[str, Any]:
        name = export_filename(filename)
        if len(contents) > MAX_EXPORT_BYTES:
            raise ValueError("Export exceeds the 32 MB limit; use Open Folder to copy larger files")
        selected = self._app.window.create_file_dialog(30, save_filename=name)
        if not selected:
            return {"status": "cancelled"}
        destination = Path(selected[0] if isinstance(selected, (tuple, list)) else selected)
        # Native save dialogs confirm overwrites; never derive a destination from page text.
        destination.write_bytes(contents)
        return {"status": "success", "path": str(destination)}

    def save_export(self, content_base64: str, filename: str, mime: str = "") -> dict[str, Any]:
        self._check_origin()
        if not isinstance(content_base64, str) or len(content_base64) > (MAX_EXPORT_BYTES * 4 // 3) + 4:
            raise ValueError("Export is too large")
        return self._save(base64.b64decode(content_base64, validate=True), filename)

    def save_download(self, url: str, filename: str) -> dict[str, Any]:
        self._check_origin()
        target, expected = urlsplit(str(url)), urlsplit(self._app.ui_url)
        if not target.scheme and str(url).startswith("/") and not str(url).startswith("//"):
            url = f"{expected.scheme}://{expected.netloc}{url}"
            target = urlsplit(url)
        if (target.scheme, target.netloc) != (expected.scheme, expected.netloc):
            raise ValueError("Exports must come from this application's local service")
        static_files = {"guide-cv-demo.csv", "coupled_template_charge.csv", "coupled_template_current_time.csv",
                        "fe_peak_measurements_template.csv", "fe_peak_method_template.json"}
        allowed_static = target.path.startswith("/ui/static/") and target.path.removeprefix("/ui/static/") in static_files
        allowed_api = bool(re.fullmatch(r"/api/v1/projects/[A-Za-z0-9_-]+/export-zip", target.path))
        if not allowed_static and not allowed_api:
            raise ValueError("Unsupported export address")
        request = Request(url, headers={"X-Electrochem-Session": self._app.manager.session_token})
        with build_opener(_NoRedirect()).open(request, timeout=15) as response:
            contents = response.read(MAX_EXPORT_BYTES + 1)
        return self._save(contents, filename)

    def save_result(self, path: str, filename: str = "") -> dict[str, Any]:
        self._check_origin()
        source = Path(str(path)).resolve()
        export_filename(source.name)
        if not source.is_file() or not known_result_file(source):
            raise ValueError("This file is not a registered processing output or project report")
        if source.stat().st_size > MAX_EXPORT_BYTES:
            raise ValueError("Use Open Folder to copy output files larger than 32 MB")
        return self._save(source.read_bytes(), filename or source.name)

    def open_external(self, url: str) -> dict[str, Any]:
        self._check_origin()
        self._app.open_link(external_web_url(url))
        return {"status": "success"}

    def open_data_dir(self) -> dict[str, Any]:
        self._check_origin()
        from electrochem_v6.core.system_service import open_path_target, register_allowed_dir

        register_allowed_dir(str(self._app.data_dir))
        return open_path_target(str(self._app.data_dir))

    def hide_to_tray(self) -> dict[str, Any]:
        self._check_origin()
        return self._app.hide_to_tray()

    def request_exit(self) -> dict[str, Any]:
        self._check_origin()
        self._app.request_exit()
        return {"status": "success"}

    def resolve_close(self, action: str) -> dict[str, Any]:
        self._check_origin()
        return self._app.resolve_close(str(action))

    def check_updates(self) -> dict[str, Any]:
        self._check_origin()
        from electrochem_v6.config import APP_VERSION

        from .updates import check_for_updates
        return check_for_updates(APP_VERSION)

    def get_mcp_configuration(self, allow_write: bool = False) -> dict[str, Any]:
        self._check_origin()
        from .mcp_integration import client_configuration

        result = client_configuration(self._app.runtime_root, self._app.data_dir, allow_write=allow_write)
        result["server_running"] = bool(self._app.manager and self._app.manager.is_running)
        result["closing"] = bool(self._app.closing_mode)
        return result

    def get_migration_plan(self) -> dict[str, Any]:
        self._check_origin()
        return self._app.get_migration_plan()

    def migrate_legacy(self, source_id: str) -> dict[str, Any]:
        self._check_origin()
        return self._app.queue_migration(str(source_id))
